# Site settings
title: Flo and Izzy's Links Page
email: your-email@domain.com
description: Flo and Izzy's Links Page
baseurl: /bgscalendar

#url: "http://www.artbymarie.info"

#collections:
#  links:
#    output: true


# Build settings
markdown: kramdown

sass:
  sass_dir: /_scss
